name: animation_viewing_companion_open
dataset:
  dialog_json: /common/home/mg1998/.cache/memeye_hf/MemEye/data/dialog/Animation_Viewing_Companion_Open.json
  image_root: /common/home/mg1998/.cache/memeye_hf/MemEye/data/image
eval:
  mode: open
  output_json: output/results_animation_viewing_companion_open.json
  max_questions: 0
