name: card_playlog_test
dataset:
  dialog_json: /Users/qingyuejiao/Desktop/MemoryBench/Benchmark_Pipeline/data/dialog/Card_Playlog_Test.json
  image_root: /Users/qingyuejiao/Desktop/MemoryBench/Benchmark_Pipeline/data/image
eval:
  output_json: output/results_card_playlog_test.json
  mode: open
  max_questions: 0
