name: chat_ui_memory_test
dataset:
  dialog_json: /common/home/mg1998/MemoryBench/Benchmark_Pipeline/data/dialog/Chat_UI_Memory_Test.json
  image_root: /common/home/mg1998/MemoryBench/Benchmark_Pipeline/data/image
eval:
  mode: open
  output_json: output/results_chat_ui_memory_test.json
  max_questions: 0
