name: comicscene_v3_candidates
dataset:
  dialog_json: /common/home/mg1998/MemoryBench/Benchmark_Pipeline/data/dialog/ComicScene_V3_candidates.json
  image_root: /common/home/mg1998/MemoryBench/Benchmark_Pipeline/data/image
eval:
  mode: mcq
  output_json: output/results_comicscene_v3_candidates.json
  max_questions: 0
