name: comicscene_v3_dev
dataset:
  dialog_json: /Users/qingyuejiao/Desktop/MemoryBench/Benchmark_Pipeline/data/dialog/ComicScene_Alley_Oop_V3_Dev.json
  image_root: /Users/qingyuejiao/Desktop/MemoryBench/Benchmark_Pipeline/data/image
eval:
  mode: mcq
  output_json: output/results_comicscene_v3_dev.json
  max_questions: 0
