name: comicscene_v3_new8
dataset:
  dialog_json: /common/home/mg1998/MemoryBench/Benchmark_Pipeline/data/dialog/ComicScene_V3_new8.json
  image_root: /common/home/mg1998/MemoryBench/Benchmark_Pipeline/data/image
eval:
  mode: open
  output_json: output/results_comicscene_v3_new8.json
  max_questions: 0
