name: multi_scene_visual_case_archive_assistant_open
dataset:
  dialog_json: /common/home/mg1998/.cache/memeye_hf/MemEye/data/dialog/Multi-Scene_Visual_Case_Archive_Assistant_Open.json
  image_root: /common/home/mg1998/.cache/memeye_hf/MemEye/data/image
eval:
  mode: open
  output_json: output/results_multi_scene_visual_case_archive_assistant_open.json
  max_questions: 0
